/* 
 * API Manager Portal
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// CallResponse
    /// </summary>
    [DataContract]
    public partial class CallResponse :  IEquatable<CallResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CallResponse" /> class.
        /// </summary>
        /// <param name="Calls">Calls.</param>
        /// <param name="CallsSize">CallsSize.</param>
        public CallResponse(List<Call> Calls = default(List<Call>), long? CallsSize = default(long?))
        {
            this.Calls = Calls;
            this.CallsSize = CallsSize;
        }
        
        /// <summary>
        /// Gets or Sets Calls
        /// </summary>
        [DataMember(Name="calls", EmitDefaultValue=false)]
        public List<Call> Calls { get; set; }

        /// <summary>
        /// Gets or Sets CallsSize
        /// </summary>
        [DataMember(Name="callsSize", EmitDefaultValue=false)]
        public long? CallsSize { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CallResponse {\n");
            sb.Append("  Calls: ").Append(Calls).Append("\n");
            sb.Append("  CallsSize: ").Append(CallsSize).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CallResponse);
        }

        /// <summary>
        /// Returns true if CallResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of CallResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CallResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Calls == other.Calls ||
                    this.Calls != null &&
                    this.Calls.SequenceEqual(other.Calls)
                ) && 
                (
                    this.CallsSize == other.CallsSize ||
                    this.CallsSize != null &&
                    this.CallsSize.Equals(other.CallsSize)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Calls != null)
                    hash = hash * 59 + this.Calls.GetHashCode();
                if (this.CallsSize != null)
                    hash = hash * 59 + this.CallsSize.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
