/* 
 * API Manager Portal
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// DeploymentBean
    /// </summary>
    [DataContract]
    public partial class DeploymentBean :  IEquatable<DeploymentBean>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            
            /// <summary>
            /// Enum DEPLOYED for "DEPLOYED"
            /// </summary>
            [EnumMember(Value = "DEPLOYED")]
            DEPLOYED,
            
            /// <summary>
            /// Enum UNDEPLOYED for "UNDEPLOYED"
            /// </summary>
            [EnumMember(Value = "UNDEPLOYED")]
            UNDEPLOYED
        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public StatusEnum? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DeploymentBean" /> class.
        /// </summary>
        /// <param name="ApiDescription">ApiDescription.</param>
        /// <param name="ApiId">ApiId.</param>
        /// <param name="ApiName">ApiName.</param>
        /// <param name="DeployDate">DeployDate.</param>
        /// <param name="DeploymentSchedule">DeploymentSchedule.</param>
        /// <param name="EnvironmentId">EnvironmentId.</param>
        /// <param name="Id">Id.</param>
        /// <param name="RevisionId">RevisionId.</param>
        /// <param name="RevisionNumber">RevisionNumber.</param>
        /// <param name="Status">Status.</param>
        public DeploymentBean(string ApiDescription = default(string), long? ApiId = default(long?), string ApiName = default(string), DateTime? DeployDate = default(DateTime?), DeploymentScheduleBean DeploymentSchedule = default(DeploymentScheduleBean), long? EnvironmentId = default(long?), long? Id = default(long?), long? RevisionId = default(long?), int? RevisionNumber = default(int?), StatusEnum? Status = default(StatusEnum?))
        {
            this.ApiDescription = ApiDescription;
            this.ApiId = ApiId;
            this.ApiName = ApiName;
            this.DeployDate = DeployDate;
            this.DeploymentSchedule = DeploymentSchedule;
            this.EnvironmentId = EnvironmentId;
            this.Id = Id;
            this.RevisionId = RevisionId;
            this.RevisionNumber = RevisionNumber;
            this.Status = Status;
        }
        
        /// <summary>
        /// Gets or Sets ApiDescription
        /// </summary>
        [DataMember(Name="apiDescription", EmitDefaultValue=false)]
        public string ApiDescription { get; set; }

        /// <summary>
        /// Gets or Sets ApiId
        /// </summary>
        [DataMember(Name="apiId", EmitDefaultValue=false)]
        public long? ApiId { get; set; }

        /// <summary>
        /// Gets or Sets ApiName
        /// </summary>
        [DataMember(Name="apiName", EmitDefaultValue=false)]
        public string ApiName { get; set; }

        /// <summary>
        /// Gets or Sets DeployDate
        /// </summary>
        [DataMember(Name="deployDate", EmitDefaultValue=false)]
        public DateTime? DeployDate { get; set; }

        /// <summary>
        /// Gets or Sets DeploymentSchedule
        /// </summary>
        [DataMember(Name="deploymentSchedule", EmitDefaultValue=false)]
        public DeploymentScheduleBean DeploymentSchedule { get; set; }

        /// <summary>
        /// Gets or Sets EnvironmentId
        /// </summary>
        [DataMember(Name="environmentId", EmitDefaultValue=false)]
        public long? EnvironmentId { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public long? Id { get; set; }

        /// <summary>
        /// Gets or Sets RevisionId
        /// </summary>
        [DataMember(Name="revisionId", EmitDefaultValue=false)]
        public long? RevisionId { get; set; }

        /// <summary>
        /// Gets or Sets RevisionNumber
        /// </summary>
        [DataMember(Name="revisionNumber", EmitDefaultValue=false)]
        public int? RevisionNumber { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DeploymentBean {\n");
            sb.Append("  ApiDescription: ").Append(ApiDescription).Append("\n");
            sb.Append("  ApiId: ").Append(ApiId).Append("\n");
            sb.Append("  ApiName: ").Append(ApiName).Append("\n");
            sb.Append("  DeployDate: ").Append(DeployDate).Append("\n");
            sb.Append("  DeploymentSchedule: ").Append(DeploymentSchedule).Append("\n");
            sb.Append("  EnvironmentId: ").Append(EnvironmentId).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  RevisionId: ").Append(RevisionId).Append("\n");
            sb.Append("  RevisionNumber: ").Append(RevisionNumber).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as DeploymentBean);
        }

        /// <summary>
        /// Returns true if DeploymentBean instances are equal
        /// </summary>
        /// <param name="other">Instance of DeploymentBean to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DeploymentBean other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ApiDescription == other.ApiDescription ||
                    this.ApiDescription != null &&
                    this.ApiDescription.Equals(other.ApiDescription)
                ) && 
                (
                    this.ApiId == other.ApiId ||
                    this.ApiId != null &&
                    this.ApiId.Equals(other.ApiId)
                ) && 
                (
                    this.ApiName == other.ApiName ||
                    this.ApiName != null &&
                    this.ApiName.Equals(other.ApiName)
                ) && 
                (
                    this.DeployDate == other.DeployDate ||
                    this.DeployDate != null &&
                    this.DeployDate.Equals(other.DeployDate)
                ) && 
                (
                    this.DeploymentSchedule == other.DeploymentSchedule ||
                    this.DeploymentSchedule != null &&
                    this.DeploymentSchedule.Equals(other.DeploymentSchedule)
                ) && 
                (
                    this.EnvironmentId == other.EnvironmentId ||
                    this.EnvironmentId != null &&
                    this.EnvironmentId.Equals(other.EnvironmentId)
                ) && 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.RevisionId == other.RevisionId ||
                    this.RevisionId != null &&
                    this.RevisionId.Equals(other.RevisionId)
                ) && 
                (
                    this.RevisionNumber == other.RevisionNumber ||
                    this.RevisionNumber != null &&
                    this.RevisionNumber.Equals(other.RevisionNumber)
                ) && 
                (
                    this.Status == other.Status ||
                    this.Status != null &&
                    this.Status.Equals(other.Status)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ApiDescription != null)
                    hash = hash * 59 + this.ApiDescription.GetHashCode();
                if (this.ApiId != null)
                    hash = hash * 59 + this.ApiId.GetHashCode();
                if (this.ApiName != null)
                    hash = hash * 59 + this.ApiName.GetHashCode();
                if (this.DeployDate != null)
                    hash = hash * 59 + this.DeployDate.GetHashCode();
                if (this.DeploymentSchedule != null)
                    hash = hash * 59 + this.DeploymentSchedule.GetHashCode();
                if (this.EnvironmentId != null)
                    hash = hash * 59 + this.EnvironmentId.GetHashCode();
                if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                if (this.RevisionId != null)
                    hash = hash * 59 + this.RevisionId.GetHashCode();
                if (this.RevisionNumber != null)
                    hash = hash * 59 + this.RevisionNumber.GetHashCode();
                if (this.Status != null)
                    hash = hash * 59 + this.Status.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
