/* 
 * API Manager Portal
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// InterceptorReferenceBean
    /// </summary>
    [DataContract]
    public partial class InterceptorReferenceBean :  IEquatable<InterceptorReferenceBean>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InterceptorReferenceBean" /> class.
        /// </summary>
        /// <param name="Id">Id.</param>
        /// <param name="IdTemp">IdTemp.</param>
        public InterceptorReferenceBean(long? Id = default(long?), long? IdTemp = default(long?))
        {
            this.Id = Id;
            this.IdTemp = IdTemp;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public long? Id { get; set; }

        /// <summary>
        /// Gets or Sets IdTemp
        /// </summary>
        [DataMember(Name="idTemp", EmitDefaultValue=false)]
        public long? IdTemp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InterceptorReferenceBean {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  IdTemp: ").Append(IdTemp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as InterceptorReferenceBean);
        }

        /// <summary>
        /// Returns true if InterceptorReferenceBean instances are equal
        /// </summary>
        /// <param name="other">Instance of InterceptorReferenceBean to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InterceptorReferenceBean other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.IdTemp == other.IdTemp ||
                    this.IdTemp != null &&
                    this.IdTemp.Equals(other.IdTemp)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                if (this.IdTemp != null)
                    hash = hash * 59 + this.IdTemp.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
