/* 
 * API Manager Portal
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing APIComponentSimpleBean
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class APIComponentSimpleBeanTests
    {
        // TODO uncomment below to declare an instance variable for APIComponentSimpleBean
        //private APIComponentSimpleBean instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of APIComponentSimpleBean
            //instance = new APIComponentSimpleBean();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of APIComponentSimpleBean
        /// </summary>
        [Test]
        public void APIComponentSimpleBeanInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" APIComponentSimpleBean
            //Assert.IsInstanceOfType<APIComponentSimpleBean> (instance, "variable 'instance' is a APIComponentSimpleBean");
        }

        /// <summary>
        /// Test the property 'ApiBroken'
        /// </summary>
        [Test]
        public void ApiBrokenTest()
        {
            // TODO unit test for the property 'ApiBroken'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'PlanBroken'
        /// </summary>
        [Test]
        public void PlanBrokenTest()
        {
            // TODO unit test for the property 'PlanBroken'
        }

    }

}
