/* 
 * API Manager Portal
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing APICreateBean
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class APICreateBeanTests
    {
        // TODO uncomment below to declare an instance variable for APICreateBean
        //private APICreateBean instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of APICreateBean
            //instance = new APICreateBean();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of APICreateBean
        /// </summary>
        [Test]
        public void APICreateBeanInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" APICreateBean
            //Assert.IsInstanceOfType<APICreateBean> (instance, "variable 'instance' is a APICreateBean");
        }

        /// <summary>
        /// Test the property 'Api'
        /// </summary>
        [Test]
        public void ApiTest()
        {
            // TODO unit test for the property 'Api'
        }
        /// <summary>
        /// Test the property 'Revision'
        /// </summary>
        [Test]
        public void RevisionTest()
        {
            // TODO unit test for the property 'Revision'
        }

    }

}
