/* 
 * API Manager Portal
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CacheMetric
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CacheMetricTests
    {
        // TODO uncomment below to declare an instance variable for CacheMetric
        //private CacheMetric instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CacheMetric
            //instance = new CacheMetric();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CacheMetric
        /// </summary>
        [Test]
        public void CacheMetricInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CacheMetric
            //Assert.IsInstanceOfType<CacheMetric> (instance, "variable 'instance' is a CacheMetric");
        }

        /// <summary>
        /// Test the property 'Itens'
        /// </summary>
        [Test]
        public void ItensTest()
        {
            // TODO unit test for the property 'Itens'
        }
        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Test]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }

    }

}
