/* 
 * API Manager Portal
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ChangeLog
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ChangeLogTests
    {
        // TODO uncomment below to declare an instance variable for ChangeLog
        //private ChangeLog instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ChangeLog
            //instance = new ChangeLog();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChangeLog
        /// </summary>
        [Test]
        public void ChangeLogInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ChangeLog
            //Assert.IsInstanceOfType<ChangeLog> (instance, "variable 'instance' is a ChangeLog");
        }

        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Test]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }
        /// <summary>
        /// Test the property 'CreationDate'
        /// </summary>
        [Test]
        public void CreationDateTest()
        {
            // TODO unit test for the property 'CreationDate'
        }
        /// <summary>
        /// Test the property 'CredentialId'
        /// </summary>
        [Test]
        public void CredentialIdTest()
        {
            // TODO unit test for the property 'CredentialId'
        }
        /// <summary>
        /// Test the property 'CredentialLogin'
        /// </summary>
        [Test]
        public void CredentialLoginTest()
        {
            // TODO unit test for the property 'CredentialLogin'
        }
        /// <summary>
        /// Test the property 'CredentialName'
        /// </summary>
        [Test]
        public void CredentialNameTest()
        {
            // TODO unit test for the property 'CredentialName'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'JsonAfter'
        /// </summary>
        [Test]
        public void JsonAfterTest()
        {
            // TODO unit test for the property 'JsonAfter'
        }
        /// <summary>
        /// Test the property 'JsonBefore'
        /// </summary>
        [Test]
        public void JsonBeforeTest()
        {
            // TODO unit test for the property 'JsonBefore'
        }
        /// <summary>
        /// Test the property 'ObjectId'
        /// </summary>
        [Test]
        public void ObjectIdTest()
        {
            // TODO unit test for the property 'ObjectId'
        }
        /// <summary>
        /// Test the property 'ObjectType'
        /// </summary>
        [Test]
        public void ObjectTypeTest()
        {
            // TODO unit test for the property 'ObjectType'
        }
        /// <summary>
        /// Test the property 'Parent'
        /// </summary>
        [Test]
        public void ParentTest()
        {
            // TODO unit test for the property 'Parent'
        }

    }

}
