/* 
 * API Manager Portal
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DeploymentSimpleBean
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DeploymentSimpleBeanTests
    {
        // TODO uncomment below to declare an instance variable for DeploymentSimpleBean
        //private DeploymentSimpleBean instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DeploymentSimpleBean
            //instance = new DeploymentSimpleBean();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeploymentSimpleBean
        /// </summary>
        [Test]
        public void DeploymentSimpleBeanInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DeploymentSimpleBean
            //Assert.IsInstanceOfType<DeploymentSimpleBean> (instance, "variable 'instance' is a DeploymentSimpleBean");
        }

        /// <summary>
        /// Test the property 'ApiId'
        /// </summary>
        [Test]
        public void ApiIdTest()
        {
            // TODO unit test for the property 'ApiId'
        }
        /// <summary>
        /// Test the property 'ApiName'
        /// </summary>
        [Test]
        public void ApiNameTest()
        {
            // TODO unit test for the property 'ApiName'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'RevisionId'
        /// </summary>
        [Test]
        public void RevisionIdTest()
        {
            // TODO unit test for the property 'RevisionId'
        }
        /// <summary>
        /// Test the property 'RevisionNumber'
        /// </summary>
        [Test]
        public void RevisionNumberTest()
        {
            // TODO unit test for the property 'RevisionNumber'
        }

    }

}
