/* 
 * API Manager Portal
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EnvironmentSimpleBean
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EnvironmentSimpleBeanTests
    {
        // TODO uncomment below to declare an instance variable for EnvironmentSimpleBean
        //private EnvironmentSimpleBean instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EnvironmentSimpleBean
            //instance = new EnvironmentSimpleBean();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EnvironmentSimpleBean
        /// </summary>
        [Test]
        public void EnvironmentSimpleBeanInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EnvironmentSimpleBean
            //Assert.IsInstanceOfType<EnvironmentSimpleBean> (instance, "variable 'instance' is a EnvironmentSimpleBean");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'InboundUrl'
        /// </summary>
        [Test]
        public void InboundUrlTest()
        {
            // TODO unit test for the property 'InboundUrl'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Test]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'RevisionDeployed'
        /// </summary>
        [Test]
        public void RevisionDeployedTest()
        {
            // TODO unit test for the property 'RevisionDeployed'
        }
        /// <summary>
        /// Test the property 'TeamVisibility'
        /// </summary>
        [Test]
        public void TeamVisibilityTest()
        {
            // TODO unit test for the property 'TeamVisibility'
        }
        /// <summary>
        /// Test the property 'Users'
        /// </summary>
        [Test]
        public void UsersTest()
        {
            // TODO unit test for the property 'Users'
        }
        /// <summary>
        /// Test the property 'VisibilityType'
        /// </summary>
        [Test]
        public void VisibilityTypeTest()
        {
            // TODO unit test for the property 'VisibilityType'
        }

    }

}
