/* 
 * API Manager Portal
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InterceptorBean
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InterceptorBeanTests
    {
        // TODO uncomment below to declare an instance variable for InterceptorBean
        //private InterceptorBean instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InterceptorBean
            //instance = new InterceptorBean();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InterceptorBean
        /// </summary>
        [Test]
        public void InterceptorBeanInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InterceptorBean
            //Assert.IsInstanceOfType<InterceptorBean> (instance, "variable 'instance' is a InterceptorBean");
        }

        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Test]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
        /// <summary>
        /// Test the property 'ExecutionPoint'
        /// </summary>
        [Test]
        public void ExecutionPointTest()
        {
            // TODO unit test for the property 'ExecutionPoint'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'IdTemp'
        /// </summary>
        [Test]
        public void IdTempTest()
        {
            // TODO unit test for the property 'IdTemp'
        }
        /// <summary>
        /// Test the property 'Operation'
        /// </summary>
        [Test]
        public void OperationTest()
        {
            // TODO unit test for the property 'Operation'
        }
        /// <summary>
        /// Test the property 'Parent'
        /// </summary>
        [Test]
        public void ParentTest()
        {
            // TODO unit test for the property 'Parent'
        }
        /// <summary>
        /// Test the property 'ParentType'
        /// </summary>
        [Test]
        public void ParentTypeTest()
        {
            // TODO unit test for the property 'ParentType'
        }
        /// <summary>
        /// Test the property 'PlanId'
        /// </summary>
        [Test]
        public void PlanIdTest()
        {
            // TODO unit test for the property 'PlanId'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Test]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'Resource'
        /// </summary>
        [Test]
        public void ResourceTest()
        {
            // TODO unit test for the property 'Resource'
        }
        /// <summary>
        /// Test the property 'Revision'
        /// </summary>
        [Test]
        public void RevisionTest()
        {
            // TODO unit test for the property 'Revision'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
