/* 
 * API Manager Portal
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OperationBean
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OperationBeanTests
    {
        // TODO uncomment below to declare an instance variable for OperationBean
        //private OperationBean instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OperationBean
            //instance = new OperationBean();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OperationBean
        /// </summary>
        [Test]
        public void OperationBeanInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OperationBean
            //Assert.IsInstanceOfType<OperationBean> (instance, "variable 'instance' is a OperationBean");
        }

        /// <summary>
        /// Test the property 'ApiBroken'
        /// </summary>
        [Test]
        public void ApiBrokenTest()
        {
            // TODO unit test for the property 'ApiBroken'
        }
        /// <summary>
        /// Test the property 'Async'
        /// </summary>
        [Test]
        public void AsyncTest()
        {
            // TODO unit test for the property 'Async'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Destination'
        /// </summary>
        [Test]
        public void DestinationTest()
        {
            // TODO unit test for the property 'Destination'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Interceptors'
        /// </summary>
        [Test]
        public void InterceptorsTest()
        {
            // TODO unit test for the property 'Interceptors'
        }
        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Test]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'Timeout'
        /// </summary>
        [Test]
        public void TimeoutTest()
        {
            // TODO unit test for the property 'Timeout'
        }
        /// <summary>
        /// Test the property 'Urls'
        /// </summary>
        [Test]
        public void UrlsTest()
        {
            // TODO unit test for the property 'Urls'
        }

    }

}
