/* 
 * API Manager Portal
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PlanResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PlanResponseTests
    {
        // TODO uncomment below to declare an instance variable for PlanResponse
        //private PlanResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PlanResponse
            //instance = new PlanResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PlanResponse
        /// </summary>
        [Test]
        public void PlanResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PlanResponse
            //Assert.IsInstanceOfType<PlanResponse> (instance, "variable 'instance' is a PlanResponse");
        }

        /// <summary>
        /// Test the property 'Api'
        /// </summary>
        [Test]
        public void ApiTest()
        {
            // TODO unit test for the property 'Api'
        }
        /// <summary>
        /// Test the property 'DefaultPlan'
        /// </summary>
        [Test]
        public void DefaultPlanTest()
        {
            // TODO unit test for the property 'DefaultPlan'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Interceptors'
        /// </summary>
        [Test]
        public void InterceptorsTest()
        {
            // TODO unit test for the property 'Interceptors'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
