/* 
 * API Manager Portal
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ResourceBean
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ResourceBeanTests
    {
        // TODO uncomment below to declare an instance variable for ResourceBean
        //private ResourceBean instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ResourceBean
            //instance = new ResourceBean();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ResourceBean
        /// </summary>
        [Test]
        public void ResourceBeanInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ResourceBean
            //Assert.IsInstanceOfType<ResourceBean> (instance, "variable 'instance' is a ResourceBean");
        }

        /// <summary>
        /// Test the property 'ApiBroken'
        /// </summary>
        [Test]
        public void ApiBrokenTest()
        {
            // TODO unit test for the property 'ApiBroken'
        }
        /// <summary>
        /// Test the property 'Config'
        /// </summary>
        [Test]
        public void ConfigTest()
        {
            // TODO unit test for the property 'Config'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Destination'
        /// </summary>
        [Test]
        public void DestinationTest()
        {
            // TODO unit test for the property 'Destination'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Interceptors'
        /// </summary>
        [Test]
        public void InterceptorsTest()
        {
            // TODO unit test for the property 'Interceptors'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Operations'
        /// </summary>
        [Test]
        public void OperationsTest()
        {
            // TODO unit test for the property 'Operations'
        }
        /// <summary>
        /// Test the property 'Timeout'
        /// </summary>
        [Test]
        public void TimeoutTest()
        {
            // TODO unit test for the property 'Timeout'
        }

    }

}
