/* 
 * API Manager Portal
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ResponseEntity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ResponseEntityTests
    {
        // TODO uncomment below to declare an instance variable for ResponseEntity
        //private ResponseEntity instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ResponseEntity
            //instance = new ResponseEntity();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ResponseEntity
        /// </summary>
        [Test]
        public void ResponseEntityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ResponseEntity
            //Assert.IsInstanceOfType<ResponseEntity> (instance, "variable 'instance' is a ResponseEntity");
        }

        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Test]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }
        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Test]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }

    }

}
