/* 
 * API Manager Portal
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RevisionSimpleBean
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RevisionSimpleBeanTests
    {
        // TODO uncomment below to declare an instance variable for RevisionSimpleBean
        //private RevisionSimpleBean instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RevisionSimpleBean
            //instance = new RevisionSimpleBean();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RevisionSimpleBean
        /// </summary>
        [Test]
        public void RevisionSimpleBeanInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RevisionSimpleBean
            //Assert.IsInstanceOfType<RevisionSimpleBean> (instance, "variable 'instance' is a RevisionSimpleBean");
        }

        /// <summary>
        /// Test the property 'ApiBroken'
        /// </summary>
        [Test]
        public void ApiBrokenTest()
        {
            // TODO unit test for the property 'ApiBroken'
        }
        /// <summary>
        /// Test the property 'CreationDate'
        /// </summary>
        [Test]
        public void CreationDateTest()
        {
            // TODO unit test for the property 'CreationDate'
        }
        /// <summary>
        /// Test the property 'Deployments'
        /// </summary>
        [Test]
        public void DeploymentsTest()
        {
            // TODO unit test for the property 'Deployments'
        }
        /// <summary>
        /// Test the property 'Destination'
        /// </summary>
        [Test]
        public void DestinationTest()
        {
            // TODO unit test for the property 'Destination'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Interceptors'
        /// </summary>
        [Test]
        public void InterceptorsTest()
        {
            // TODO unit test for the property 'Interceptors'
        }
        /// <summary>
        /// Test the property 'LifeCycle'
        /// </summary>
        [Test]
        public void LifeCycleTest()
        {
            // TODO unit test for the property 'LifeCycle'
        }
        /// <summary>
        /// Test the property 'Resources'
        /// </summary>
        [Test]
        public void ResourcesTest()
        {
            // TODO unit test for the property 'Resources'
        }
        /// <summary>
        /// Test the property 'RevisionNumber'
        /// </summary>
        [Test]
        public void RevisionNumberTest()
        {
            // TODO unit test for the property 'RevisionNumber'
        }
        /// <summary>
        /// Test the property 'Timeout'
        /// </summary>
        [Test]
        public void TimeoutTest()
        {
            // TODO unit test for the property 'Timeout'
        }

    }

}
